package com.adolfogonzalez.mareasihmpro.ui
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.*
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.*
import com.adolfogonzalez.mareasihmpro.data.AppData

@Composable fun Page(title:String,compact:Boolean,content:@Composable ColumnScope.()->Unit){Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(horizontal=if(compact)28.dp else 24.dp,vertical=if(compact)18.dp else 24.dp),horizontalAlignment=Alignment.CenterHorizontally){Text(title,color=Cyan,fontWeight=FontWeight.Bold,fontSize=if(compact)14.sp else 22.sp);Spacer(Modifier.height(8.dp));content();Spacer(Modifier.height(if(compact)42.dp else 28.dp))}}
@Composable fun Home(data:AppData,compact:Boolean)=Page("MAREAS IHM PRO",compact){Text(data.station,color=Green,fontSize=10.sp,textAlign=TextAlign.Center);Text("${"%.2f".format(data.tideHeight)} m",color=Color.White,fontSize=36.sp,fontWeight=FontWeight.Black);Text(if(data.rising)"FLUJO ↑" else "REFLUJO ↓",color=Cyan);data.tideEvents.firstOrNull()?.let{val label=if(it.type.lowercase().startsWith("pl"))"Pleamar" else "Bajamar";Text("$label ${it.time}",color=Color.White)};Stat("Temperatura","${data.temperature.toInt()} °C",Amber);Stat("Viento","${data.wind.toInt()} km/h",Cyan);Stat("Oleaje","${"%.1f".format(data.wave)} m",Purple);Stat("UV","${"%.1f".format(data.uv)}",Amber);Stat("Luna","${data.moonLabel} · ${data.moonIllumination}%",Purple);Stat("Coeficiente","${data.coefficient}",Purple)}
@Composable fun Tides(data:AppData,compact:Boolean)=Page("MAREAS +24H",compact){Chart(data.tideCurve,Cyan,Modifier.fillMaxWidth().height(if(compact)125.dp else 230.dp));Axis();data.tideEvents.forEach{val high=it.type.lowercase().startsWith("pl");Stat(if(high)"Pleamar" else "Bajamar","${it.time} · ${"%.2f".format(it.height)} m",if(high)Cyan else Amber)}}
@Composable fun Weather(data:AppData,compact:Boolean)=Page("TIEMPO",compact){Text("${data.temperature.toInt()}°",color=Color.White,fontSize=42.sp,fontWeight=FontWeight.Black);Chart(data.temperatureCurve,Amber,Modifier.fillMaxWidth().height(if(compact)105.dp else 180.dp));Axis();Stat("Sensación","${data.feels.toInt()} °C",Amber);Stat("Humedad","${data.humidity}%",Cyan);Stat("Presión","${data.pressure.toInt()} hPa",Purple)}
@Composable fun Wind(data:AppData,compact:Boolean)=Page("VIENTO",compact){Text(compass(data.windDirection),color=Cyan,fontSize=38.sp,fontWeight=FontWeight.Black);Stat("Velocidad","${data.wind.toInt()} km/h",Cyan);Stat("Rachas","${data.gusts.toInt()} km/h",Amber);Chart(data.windCurve,Cyan,Modifier.fillMaxWidth().height(if(compact)90.dp else 150.dp));Axis();Chart(data.gustCurve,Amber,Modifier.fillMaxWidth().height(if(compact)90.dp else 150.dp))}
@Composable fun Sea(data:AppData,compact:Boolean)=Page("OLEAJE Y MAR",compact){Stat("Altura","${"%.1f".format(data.wave)} m",Cyan);Stat("Periodo","${data.period.toInt()} s",Purple);Stat("Dirección","${data.waveDirection.toInt()}°",Cyan);Stat("Mar de fondo","${"%.1f".format(data.swell)} m",Purple);Stat("Temperatura agua","${data.seaTemperature.toInt()} °C",Cyan)}
@Composable fun UV(data:AppData,compact:Boolean)=Page("RADIACIÓN UV",compact){Text("${"%.1f".format(data.uv)}",color=Amber,fontSize=42.sp,fontWeight=FontWeight.Black);Text(uvLevel(data.uv),color=Green);Chart(data.uvCurve,Amber,Modifier.fillMaxWidth().height(if(compact)105.dp else 180.dp));Axis();Stat("Protección",if(data.uv<3)"Básica" else "Crema y gafas",Green)}
@Composable fun Beach(data:AppData,compact:Boolean)=Page("MODO PLAYA",compact){val score=(if(data.uv<8)1 else 0)+(if(data.wave<1.2)1 else 0)+(if(data.wind<25)1 else 0);Text(if(score==3)"EXCELENTE" else if(score==2)"BUENA" else "REGULAR",color=if(score>=2)Green else Amber,fontSize=28.sp,fontWeight=FontWeight.Black);Stat("Oleaje","${"%.1f".format(data.wave)} m",Cyan);Stat("UV","${"%.1f".format(data.uv)}",Amber);Stat("Viento","${data.wind.toInt()} km/h",Cyan);Stat("Agua","${data.seaTemperature.toInt()} °C",Purple)}
@Composable fun Fishing(data:AppData,compact:Boolean)=Page("MODO PESCA",compact){val favorable=data.coefficient>75&&data.wind<25;Text(if(favorable)"FAVORABLE" else "NORMAL",color=if(favorable)Green else Amber,fontSize=28.sp,fontWeight=FontWeight.Black);Stat("Coeficiente","${data.coefficient}",Purple);Stat("Luna",data.moonLabel,Purple);data.tideEvents.take(2).forEach{Stat(if(it.type.lowercase().startsWith("pl"))"Pleamar" else "Bajamar",it.time,if(it.type.lowercase().startsWith("pl"))Cyan else Amber)};Stat("Presión","${data.pressure.toInt()} hPa",Cyan)}
@Composable fun Moon(data:AppData,compact:Boolean)=Page("LUNA Y COEFICIENTE",compact){Text(data.moonLabel,color=Purple,fontSize=28.sp,fontWeight=FontWeight.Black);Stat("Iluminación","${data.moonIllumination}%",Amber);Stat("Coeficiente","${data.coefficient}",Purple);Stat("Tipo",if(data.coefficient>85)"Marea viva" else if(data.coefficient<55)"Marea muerta" else "Marea media",Cyan)}
private fun compass(d:Double)=arrayOf("N","NE","E","SE","S","SW","W","NW")[((d/45).toInt()+8)%8]
private fun uvLevel(v:Double)=if(v<3)"Bajo" else if(v<6)"Moderado" else if(v<8)"Alto" else if(v<11)"Muy alto" else "Extremo"
